# Task: Create a function that finds the nth Fibonacci number
# Generated by Navi Agent Team

```python
def fibonacci(n: int) -> int:
    """
    Calculate the nth Fibonacci number.

    Args:
        n (int): The position of the Fibonacci number to calculate.

    Returns:
        int: The nth Fibonacci number.

    Raises:
        ValueError: If n is less than 0.
    """

    # Check if n is a non-negative integer
    if not isinstance(n, int) or n < 0:
        raise ValueError("n must be a non-negative integer")

    # Base cases for the Fibonacci sequence
    if n == 0:
        return 0
    elif n == 1:
        return 1

    # Initialize variables to store the last two numbers in the sequence
    fib_prev = 0
    fib_curr = 1

    # Calculate the nth Fibonacci number using a loop
    for _ in range(2, n + 1):
        # Update the current and previous Fibonacci numbers
        fib_next = fib_prev + fib_curr
        fib_prev = fib_curr
        fib_curr = fib_next

    return fib_curr
```