# Task: search
# Generated by Navi Agent Team

```python
import re

class SearchEngine:
    """
    A simple search engine that searches for keywords in a given text.
    
    Attributes:
        text (str): The text to be searched.
        
    Methods:
        search_keyword(keyword): Searches the keyword in the text and returns its occurrences.
    """

    def __init__(self, text):
        """
        Initializes the SearchEngine with the given text.
        
        Args:
            text (str): The text to be searched.
        """
        self.text = text

    def search_keyword(self, keyword):
        """
        Searches the keyword in the text and returns its occurrences.
        
        Args:
            keyword (str): The keyword to be searched.
            
        Returns:
            list: A list of tuples containing the start and end positions of each occurrence.
        """
        try:
            # Use regular expression to find all occurrences of the keyword
            pattern = re.compile(re.escape(keyword), re.IGNORECASE)
            occurrences = [(m.start(), m.end()) for m in pattern.finditer(self.text)]
            
            return occurrences
        
        except Exception as e:
            print(f"An error occurred: {str(e)}")
            return None

# Example usage
if __name__ == "__main__":
    text = "The quick brown fox jumps over the lazy dog. The dog is very sleepy."
    
    search_engine = SearchEngine(text)
    keyword = "the"
    occurrences = search_engine.search_keyword(keyword)
    
    if occurrences:
        print(f"Occurrences of '{keyword}':")
        for occurrence in occurrences:
            start, end = occurrence
            print(f"{start}: {text[start:end]}")
```